### Задание 1

Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг   !!!
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [60]:
import pandas as pd
 
# Получение данных из файлов
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

def class_f (rait_in):
    """
    Функция, которая классифицирует фильмы по следующим правилам:
        * оценка 2 и меньше - низкий рейтинг;
        * оценка меньше чем 4.5 - средний рейтинг;
        * оценка 4.5 и 5 - высокий рейтинг;
    """
    if rait_in <= 2:
        class_v = 'Низкий'
    elif rait_in > 2 and rait_in < 4.5:
        class_v = 'Средний'
    elif rait_in >= 4.5:
        class_v = 'Высокий'
    return class_v

# Вычисление среднего рейтинга фильма и добавления столба среднего рейтинга 
rated = ratings.groupby('movieId').mean().merge(movies, on='movieId', how='left')
rated.drop(['userId', 'timestamp'], axis='columns', inplace=True)

# Классификация фильмов через функцию
rated['class'] = rated['rating'].apply(class_f)

rated.head()

,movieId,rating,title,genres,class
0,1,3.872470,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Средний
1,2,3.401869,Jumanji (1995),Adventure|Children|Fantasy,Средний
2,3,3.161017,Grumpier Old Men (1995),Comedy|Romance,Средний
3,4,2.384615,Waiting to Exhale (1995),Comedy|Drama|Romance,Средний
4,5,3.267857,Father of the Bride Part II (1995),Comedy,Средний

### Задание 2

Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

In [110]:
import pandas as pd
 
# Получение данных из файлов
keywords = pd.read_csv('keywords.csv')

geo_data = {'Центр': ['москв', 'тул', 'ярославл'],
            'Северо-Запад': ['петербург', 'псков', 'мурманск'],
            'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск'] }

def geo_class (keyword_in, geo_dict):
    """
    Функция гео-классификатор
    """
    locat = 'undefined'
    for key in geo_dict.keys():
        for value in geo_dict[key]:
            if value in keyword_in:
                locat = key
    return locat

keywords['region'] = keywords['keyword'].apply(geo_class, geo_dict=geo_data)
keywords[1010:1015]

                    keyword   shows     region
1010         политнавигатор  182579  undefined
1011            банк москвы  182666      Центр
1012                    май  182503  undefined
1013  кредитный калькулятор  184110  undefined
1014            живая сталь  182437  undefined

### Задание 3 (бонусное)

Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

В переменную years запишите список из всех годов с 1950 по 2010.

Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

для каждой строки пройдите по всем годам списка years
если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга