### Задание 1

Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

<ul>
<li>если источник traffic_source равен yandex или google, то в source_type ставится organic</li>
<li>для источников paid и email из России - ставим ad</li>
<li>для источников paid и email не из России - ставим other</li>
<li>все остальные варианты берем из traffic_source без изменений</li>
</ul>

In [4]:
import pandas as pd

def source_t_f(row):
    """
    Функция, определяющая source_type.
    Входными данными является DataFrame - Row.
    """
    source_t_v = row['traffic_source']
    if row['traffic_source'] == 'yandex' or row['traffic_source'] == 'google':
        source_t_v = 'organic'
    elif row['traffic_source'] == 'paid' or row['traffic_source'] == 'email':
        if row['region'] == 'Russia':
            source_t_v = 'ad'  
        else:
            source_t_v = 'other'
    return source_t_v
    
log = pd.read_csv('visit_log.csv', sep=';')
log['source_type'] = log.apply(source_t_f, axis=1)

log.loc[log.traffic_source == 'email']

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad
20,1549980816,de47c9b27e,https://host.ru/8fe7c39e5c598bbc54,Ukraine,2f25b6e26a,email,other
23,1549980839,015275e61f,https://host.ru/c8d9213a31839f9a3a,Russia,21bdc57777,email,ad
27,1549980853,ea49aa9f6f,https://host.ru/1afc5618562365020a,Russia,20e8e91ecf,email,ad
33,1549980897,7f9c9e31ac,https://host.ru/ac2d98a5a63e7c6e28,Belarus,38f45e7f9b,email,other
...,...,...,...,...,...,...,...
18904,1550094129,db3ed9712d,https://host.ru/186c4d6b47dbde0e74,Russia,6a670538ac,email,ad
18905,1550094130,0f83f523bd,https://host.ru/c8d9213a31839f9a3a,Russia,f0ad6c3a39,email,ad
18921,1550094218,b9723ef95e,https://host.ru/c8d9213a31839f9a3a,Ukraine,6d616e3a35,email,other
18923,1550094221,42af1bbaa1,https://host.ru/6fda01ec57f23abc9e,Russia,a15d5f2ad9,email,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,ad

### Задание 2

В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:

<ol>
<li>Прочитайте содержимое файла с датафрейм</li>
<li>Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном</li>
</ol>

In [5]:
url_txt = pd.read_csv('URLs.txt')
url_txt.loc[url_txt.url.str.contains('\/\d{8}\-', regex = True)]

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

### Задание 3

В датафрейме data создайте столбец lemmas, в котором вычислите леммы поисковых запросов из столбца keyword. Леммы должны иметь строковый тип.

In [35]:
from pymystem3 import Mystem

def lemm_f (key):
    m = Mystem()
    lemmas = m.lemmatize(key)
    final_l = set(lemmas)
    final_l.remove('\n')
    final_l.remove(' ')
    lemmas = list(final_l)
    final_l = ''
    for word in lemmas:
        final_l += word + ','     
    return final_l

data = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

data['lemmas'] = data['keyword'].apply(lemm_f)
data.head()

                 keyword   shows                lemmas
0    курс гривны к рублю  125076  гривна,курс,к,рубль,
1        доллары в рубли  114173       доллар,в,рубль,
2  100 долларов в рублях   97534   100,доллар,в,рубль,
3             курс рубля   53546           курс,рубль,